version: '3.8'
services:
  database:
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "postgres"]
      interval: 1s
      retries: 30
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - PORT=3000  # Add this line
    depends_on:
      database:
        condition: service_healthy
        required: true
      run-migrations:
        condition: service_completed_successfully
        required: true
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  run-migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: run-migrations
    environment:
      - DB_HOST=database
    depends_on:
      database:
        condition: service_healthy
        required: true
    env_file:
      - .env

volumes:
  postgres_data: